# made by kvbvs
import discord
from discord.ext.commands import *
from discord.ext import commands
import random
import asyncio
import time
import json
from itertools import cycle
import time
from threading import Thread
from random import randint
import datetime
import os
import aiohttp
import sys
import traceback
import json
from discord.utils import get

 
##Prefix##

bot = commands.Bot(command_prefix='n!')

client = commands.Bot(command_prefix='n!')

##OtherStuff##
bot.remove_command('flood')



##AreBotRedy##
@bot.event
async def on_ready():
#BotInfo#
    print(f"open-source code")
    print("Bot are online! Ready to spam...")
    print(f"Bot Status: Online")


##banner, need permissions##
@bot.command(pass_context=True)
async def ban(ctx, member : discord.Member):
    await member.ban()
    await ctx.message.delete()

 
##Sspammer, need permissions##
@bot.command(pass_context=True)
async def spam(ctx): #run "n!flood" to run the spam
    await ctx.message.delete()
    while True:
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        await ctx.send("Haha, u get rekt! @everyone")
        
        
        
##Role creator##
@bot.command(pass_context=True)
async def roles(ctx):
    await ctx.message.delete()
    while True:
        guild = ctx.guild
        await guild.create_role(name="GET ")



##Channel spammer##
@bot.command(pass_context=True)
async def channels(ctx):
    await ctx.message.delete()
    guild = ctx.message.guild
    await guild.create_text_channel('Created by kvbvs') 
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')
    await guild.create_text_channel('Created by kvbvs')




##bot token##
bot.run ("ur token")
